## Matthew Basthon 2014-2016
## Shiny UI for 450k classifier 

# For display later  
AppName <- "MAC: Methylation Array Classifier"
AppVersion <- "1.3.2-2.1"

library(shiny) # load shiny at beginning at both scripts
library(shinythemes)
shinyUI(fluidPage(theme = shinytheme("united"),
                  
                  titlePanel(AppName), # give the interface a title 
                  
                  br(),
                  sidebarLayout(
                    
                    sidebarPanel( # all the UI controls go in here
                      width=3,
                      fileInput('file1', 'Zip file upload:',
                                accept=c('application/zip', 
                                         '.zip')
                      ),
                      helpText("MAC will classify illumina X50k array medulloblastoma methylation data in to one of four molecular subgroups"),
                      "Download test data to try classifier:", a(href="test-set.zip", "Test ZIP file", target="_blank"), helpText("Array processing and classification takes ~70 seconds for this test set of 24 arrays")
                    ), # End sidebarPanel
                    
                    
                    mainPanel( # all of the output elements go here
                      tabsetPanel(
                        id = 'sequenom',
                        tabPanel('Classification Table', dataTableOutput('classification_table'), br(), helpText("Unclassifiable samples are those for which a confident subgroup call could not be made"), br(), downloadButton('downloadClassification', 'Download table as .csv'),p(), br(), textOutput("time")),
                        tabPanel('Classification Plot', plotOutput("classifierPlot", height = "640", width = "auto"), br(), helpText("Unclassifiable and Array QC failed samples are not shown in this plot.  Boxes show the confidence interval for subgroup assignment generated by bootstrapping, and the individual data points represent the final probability associated with each subgroup call."), br(), downloadButton('PlotDownload', 'Download plot as high-res .png'), p()),
                        tabPanel('β-value density plot', br(), uiOutput("ui"), plotOutput("DensityPlot", height = "640", width = "auto"), br(), downloadButton('DenistyPlotDownload', 'Download plot as high-res .png'), p()),
                        tabPanel('β-value density bean plot', plotOutput("DensityBeanPlot", height = "640", width = "auto"), br(), downloadButton('DenistyBeanPlotDownload', 'Download plot as high-res .png'), p()),
                        tabPanel('Sample QC', br(), p(), textOutput("fs"), br(), textOutput("fc")
                                 #, br(), "Table below shows the number of missing values for each Array:", br(), p(), dataTableOutput('NA_table'), br()
                                 ),
                        #tabPanel('β-values', dataTableOutput('Beta'), br(), downloadButton('downloadBeta', 'Download table as .csv')),
                        tabPanel('About',
                                 h4(AppName, AppVersion),
                                 br(),
                                 p("Machine learning and classifier code: ", a("Reza Rafiee", href="mailto:Gholamreza.Rafiee@newcastle.ac.uk?subject=Sequenom classifier website")),
                                 p("Shiny web app code and adaptation: ", a("Matthew Bashton", href="mailto:matthew.bashton@newcastle.ac.uk?subject=Sequenom classifier website")),
                                 p("Project concept: ", a("Ed Schwalbe", href="mailto:ed.schwalbe@newcastle.ac.uk?subject=Sequenom classifier website")),
                                 br(),
                                 h4("Overview"),
                                 p(AppName, "will classify illumina 450k and EPIC medulloblastoma methylation array data in to one of four molecular subgroups: WNT, SHH, Group 3 and Group 4."),
                                 p("In summary the classifier works as described below:"),
                                 tags$ol(
                                   tags$li("illumina 450k or EPIC data is normalised using the preprocessNoob function from", 
                                   a("minfi.", href="http://bioconductor.org/packages/release/bioc/html/minfi.html")), p(),
                                   tags$li("The detection", em("p-value"), "for each probe on each array is obtained using minif, should any one array have more than 5% of its probes with a detection", em("p"), "-value, of grater than 0.05 these arrays are considered to have failed Array QC and will not be amenable to classification."), p(),
                                   tags$li("The β-values of 10,000 probes used in our classifier are then extracted from normalised data for each sample."), p(),
                                   tags$li("The 10,000 β-values for each sample are projected into the metagene space of our existing model, this is derived from the 450k data of our discovery cohort of 434 medulloblastoma samples."), p(),
                                   tags$li("A multi-class optimised", a("Support Vector Machine", href="https://en.wikipedia.org/wiki/Support_vector_machine"), "(SVM) validated and trained on 220 samples from our 450k medulloblastoma cohort is used to robustly assign subgroup to the projected test set produced in the previous step."), p(),
                                   tags$ul(
                                     tags$li("Our SVM is validated using a bootstrapping technique via 1,000 random iterations of 80% of the training set, confidence interval derived from this is plotted on the Classification Graph as a box plot."), p(),
                                     tags$li("The final probability assignment for a subgroup call is made by creating an SVM model with the whole (220 sample) 450k training set; these probabilities are given in the Classification Table in the initial tab."), p(),
                                     tags$li("Calls made with a probability below our predefined threshold are considered unreliable and samples will be labeled as Unclassifiable in the Classification Table, these samples will not be plotted in the Classification Graph."), p()
                                   ),
                                   tags$li("Various post processing and formatting operations on the data take place with the interactive website being implemented in the R", a("Shiny", href = "http://shiny.rstudio.com"), "reactive web application framework."), p()
                                 ), # End ol
                                 br(),
                                 h4("Reference"),
                                 p("A manuscript is in preparation."),
                                 p(), br(),
                                 h4("Download"),
                                 "The R code for this", a("Shiny", href = "http://shiny.rstudio.com/"), "based website including training and validation cohorts can be downloaded from", a("GitHub", href = "https://github.com/MattBashton/MAC"), "the website can also be run locally using", a("Rstudio", href = "https://www.rstudio.com/"), "instructions and dependancies are outlined on GitHub.",
                                 p(), br(),
                                 h4("Funding"),
                                 p(AppName, "development was funded by a Cancer Research UK program grant.")
                        ),
                        tabPanel('Help',h4("How to use our Classifier"),
                        p(AppName, "will classify 450k microarray medulloblastoma methylation data in to one of four molecular subgroups.  To use the classifier follow the steps outlined below:"),
                        tags$ol(
                          tags$li("A compressed", a("ZIP", href="https://en.wikipedia.org/wiki/Zip_(file_format)"), "(.zip) file containing all illumina red and green channel .idat files as well as a sampleSheet.csv file is needed as input to use the classifier (see Input file fromat below for details).  If you would like to test drive the classifier,  or would like to see what an archive should contain a test zip file can be downloaded using the link in the grey box on the left."),
                          p(), img(src = "step1.png"), p(), br(),
                          tags$li("A ZIP file can then be uploaded by clicking on the 'Chose File' or 'Browse...' (browser dependent) button on the left, once uploaded the classification happens automatically."),
                          p(), img(src = "step2.png"), p(), br(),
                          tags$li("By default the Classification Table output is preselected and will present you with a four subgroup Medulloblastoma classification for each of your samples.  Other tabs presenting other information can then be accessed by clicking their names present at the top of the main panel."),
                          p(), img(src = "step3.png"), p(), br(),
                          tags$li("The contents of Tables can be downloaded by clicking the grey download button, these .csv files can then be loaded into Excel or other spreadsheet software if required."),
                          p(), img(src = "step4.png"), p(), br(),
                          tags$li("The Classification Plot can also be downloaded as a .png by clicking on the grey Download button at the bottom of the Classification Plot tab."),
                          p(), img(src = "step5.png"), br()
                        ), # End of list
                        p(), br(),
                        h4("Input file format"),
                        p("Each array on a illumina Infinium chip produces two corresponding files such as: 9403904132_R01C01_Grn.idat and 9403904132_R01C01_Red.idat; there will be a total of 12 (450k) or 8 (EPIC) these on each chip.  The first part of the file name corresponds to the Sentrix barcode and the second to the location on the chip of the sample.  All pairs of idats for each array need to be zipped up into a ZIP archive along with a ", a("CSV", href="https://en.wikipedia.org/wiki/Comma-separated_values"), " file SampleSheet.csv in order to be uploaded to the classifier."),
                        p("The SampleSheet.csv file takes the format of:"),
                        br(),
                        pre(
"[Header],,,,,,
Investigator_Name,,,,,,
Project_Name,,,,,,
Experiment_Name,,,,,,
Date,16/02/14,,,,,
,,,,,,
,,,,,,
[Data],,,,,,
Sample_Name,Sample_Plate,Sample_Group,Sample_Well,Pool_ID,Sentrix_ID,Sentrix_Position
Sample1,11,,D01,,9421912041,R04C01
Sample2,11,,E01,,9421912041,R05C01
Sample3,11,,F01,,9421912041,R06C01
Sample4,11,,A02,,9421912041,R01C02
Sample5,11,,B02,,9421912041,R02C02
Sample6,11,,C02,,9421912041,R03C02"),
                        br(),
                        p("The size and content of the header section will be dynamically skipped by ", AppName, " as long as the column ID row is present and formated like this: "),
                        pre("Sample_Name,Sample_Plate,Sample_Group,Sample_Well,Pool_ID,Sentrix_ID,Sentrix_Position"),
                        p("Following on from the header, each line corresponds to a sample on the chip(s) for the .idat files present, with the first column containing the sample name and columns six and seven corresponding to the Sentrix ID and row column position on the chip; these two strings ", strong("must"), " match up with the file naming convention mentioned above."),
                        p("The SampleSheet.csv file", strong("must"), "be included in the ZIP achive in order for ", AppName, " to assocate each pair of idats with each sample, failure to do so will prevent the classifier working.  Finally the last line in the sampleSheet.csv", strong("must"), "be terminated with a carriage return."),
                        p(), br(),
                        h4("Suppport"),
                        "If you have any issues with using", AppName, "please contact ",
                        a("Matthew Bashton.", href="mailto:matthew.bashton@newcastle.ac.uk?subject=Sequenom classifier website")
                        ) 
                    ), # End of tabsetPanel
                    br(),
                    hr(),
                    p("WARNING:", AppName, "is for research use only, and should only be used on samples with a confirmed histopathological diagnosis of medulloblastoma."),
                    hr(),
                    img(src = "nicr.png"), img(src = "ncl.png"),
                    br()
                  ) # End of mainPanel
                  
) # End sidebarLayout

) # End fluidPage

) # End shinyUI
