## Matthew Basthon 2014-2016
## Shiny UI for 450k classifier 

# For display later  
AppName <- "MAC: Methylation Array Classifier"
AppVersion <- "1.3.2"

library(shiny) # load shiny at beginning at both scripts
library(shinythemes)
shinyUI(fluidPage(theme = shinytheme("united"),
                  
                  titlePanel(AppName), # give the interface a title 
                  
                  br(),
                  sidebarLayout(
                    
                    sidebarPanel( # all the UI controls go in here
                      width=3,
                      fileInput('file1', 'R CSV file upload:',
                                accept=c('text/csv', 
                                         'text/comma-separated-values,text/plain', 
                                         '.csv')
                      ),
                      helpText("MAC will classify 450k array medulloblastoma methylation data in to one of four molecular subgroups"),
                      "Download test data to try classifier:", a(href="GSE54880_test_set.csv", "Test CSV file", target="_blank")
                    ), # End sidebarPanel
                    
                    
                    mainPanel( # all of the output elements go here
                      tabsetPanel(
                        id = 'sequenom',
                        #tabPanel('Classification Table', dataTableOutput('classification_table'), br(), helpText("Unclassifiable samples are those for which a confident subgroup call could not be made"), br(), downloadButton('downloadClassification', 'Download table as .csv'),p(), br(), textOutput("time")),
                        tabPanel('Classification Plot', plotOutput("classifierPlot", height = "640", width = "auto"), br(), helpText("Unclassifiable and Array QC failed samples are not shown in this plot.  Boxes show the confidence interval for subgroup assignment generated by bootstrapping, and the individual data points represent the final probability associated with each subgroup call."), br(), downloadButton('PlotDownload', 'Download plot as high-res .png'), p()),
                        #tabPanel('Sample QC', br(), p(), textOutput("fs"), br(), textOutput("fc")),
                        #tabPanel('β-values', dataTableOutput('Beta'), br(), downloadButton('downloadBeta', 'Download table as .csv')),
                        tabPanel('About',
                                 h4(AppName, AppVersion),
                                 br(),
                                 p("Machine learning and classifier code: ", a("Reza Rafiee", href="mailto:Gholamreza.Rafiee@newcastle.ac.uk?subject=Sequenom classifier website")),
                                 p("Shiny web app code and adaptation: ", a("Matthew Bashton", href="mailto:matthew.bashton@newcastle.ac.uk?subject=Sequenom classifier website")),
                                 p("Project concept: ", a("Ed Schwalbe", href="mailto:ed.schwalbe@newcastle.ac.uk?subject=Sequenom classifier website")),
                                 br(),
                                 h4("Overview"),
                                 p(), br(),
                                 h4("Reference"),
                                 p("A manuscript is in preparation."),
                                 p(), br(),
                                 h4("Download"),
                                 "The R code for this", a("Shiny", href = "http://shiny.rstudio.com/"), "based website including training and validation cohorts can be downloaded from", a("GitHub", href = "https://github.com/MattBashton/MAC"), "the website can also be run locally using", a("Rstudio", href = "https://www.rstudio.com/"), "instructions and dependancies are outlined on GitHub.",
                                 p(), br(),
                                 h4("Funding"),
                                 p(AppName, "development was funded by a Cancer Research UK program grant.")
                        ),
                        tabPanel('Help',h4("How to use our Classifier"),
                        p(AppName, "will classify 450k microarray medulloblastoma methylation data in to one of four molecular subgroups.  To use the classifier follow the steps outlined below:"),
                        p(), br(),
                        h4("Input file format"),
                        
                        p(), br(),
                        h4("Suppport"),
                        "If you have any issues with using", AppName, "please contact ",
                        a("Matthew Bashton.", href="mailto:matthew.bashton@newcastle.ac.uk?subject=Sequenom classifier website")
                        ) 
                    ), # End of tabsetPanel
                    br(),
                    hr(),
                    p("WARNING:", AppName, "is for research use only, and should only be used on samples with a confirmed histopathological diagnosis of medulloblastoma."),
                    hr(),
                    img(src = "nicr.png"), img(src = "ncl.png"),
                    br()
                  ) # End of mainPanel
                  
) # End sidebarLayout

) # End fluidPage

) # End shinyUI
